home/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # pages
    url(r'^$', homepage, name='homepage'),
    url(r'^print/$', print_invoice, name='print'),
    url(r'^print_invoicea5/$', print_invoicea5, name='print_invoicea5'),
    url(r'^printBill/$', print_bill, name='print_bill'),
    url(r'^print_billA5/$', print_billA5, name='print_billA5'),
    url(r'^print_bill_thermal/$', print_bill_thermal, name='print_bill_thermal'),
    url(r'^index/$', index, name='index'),
    url(r'^sales/$', sales, name='sales'),
    url(r'^purchase/$', puchase, name='puchase'),
    url(r'^product/$', product, name='product'),
    url(r'^hsnCategory/$', hsn_and_category, name='hsn'),
    url(r'^salesReport/$', salesReport, name='salesReport'),
    url(r'^bookingList/$', bookingList, name='bookingList'),
    url(r'^purchaseReport/$', purchaseReport, name='purchaseReport'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^generalSetting/$', generalSetting, name='generalSetting'),
    url(r'^settings/$', settings, name='settings'),
    url(r'^manage_invoice/$', manage_invoice, name='manage_invoice'),
    url(r'^expense/$', expense, name='expense'),
    url(r'^manageUser/$', manageUser, name='manageUser'),
    url(r'^WareHouse/$', wareHouseList, name='WareHouse'),
    url(r'^loginPage/$', loginPage, name='loginPage'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^report/$', report, name='report'),
    url(r'^contact/customer_ledger/(?P<id>[0-9]+)/$', customer_ledger, name='customer_ledger'),
    url(r'^contact/supplier_ledger/(?P<id>[0-9]+)/$', supplier_ledger, name='supplier_ledger'),
    url(r'^customer_due_list/$', customer_due_list, name='customer_due_list'),
    url(r'^reminder_list/$', reminder_list, name='reminder_list'),

    # customer
    url(r'^CustomerListJson/$', CustomerListJson.as_view(), name='CustomerListJson'),
    url(r'^CustomerDueListJson/$', CustomerDueListJson.as_view(), name='CustomerDueListJson'),
    url(r'^get_customer_due_list_by_date_range/$', get_customer_due_list_by_date_range,
        name='get_customer_due_list_by_date_range'),

    url(r'^api/PostCustomerDetail/$', post_customer, name='post_customer'),
    url(r'^api/GetCustomerList/$', get_customer_list, name='get_customer_list'),
    url(r'^api/GetCustomerDetail/(?P<id>[0-9]+)/$', get_customer_detail, name='get_customer_detail'),
    url(r'^api/GetCustomerDetailByName/$', get_customer_detail_by_name, name='get_customer_detail_by_name'),

    url(r'^api/EditCustomerDetail/$', edit_customer, name='edit_customer'),
    url(r'^api/DeleteCustomerDetail/$', delete_customer, name='delete_customer'),

    # supplier
    url(r'^SupplierListJson/$', SupplierListJson.as_view(), name='SupplierListJson'),

    url(r'^api/PostSupplierDetail/$', post_supplier, name='post_supplier'),
    url(r'^api/GetSupplierList/$', get_supplier_list, name='get_supplier_list'),
    url(r'^api/GetSupplierDetail/(?P<id>[0-9]+)/$', get_supplier_detail, name='get_supplier_detail'),
    url(r'^api/GetSupplierDetailByName/$', get_supplier_detail_by_name, name='get_supplier_detail_by_name'),
    url(r'^api/EditSupplierDetail/$', edit_supplier, name='edit_supplier'),
    url(r'^api/DeleteSupplierDetail/$', delete_supplier, name='delete_supplier'),

    # HSN
    url(r'^HsnListJson/$', HsnListJson.as_view(), name='HsnListJson'),

    url(r'^api/PostHsnDetail/$', post_hsn, name='post_hsn'),
    url(r'^api/GetHsnList/$', get_hsn_list, name='get_hsn_list'),
    url(r'^api/GetHSNDetail/(?P<id>[0-9]+)/$', get_hsn_detail, name='get_hsn_detail'),
    url(r'^api/EditHSNDetail/$', edit_hsn, name='edit_hsn'),
    url(r'^api/DeleteHSNDetail/$', delete_hsn, name='delete_hsn'),

    # Category
    url(r'^CategoryListJson/$', CategoryListJson.as_view(), name='CategoryListJson'),

    url(r'^api/PostCategoryDetail/$', post_category, name='post_category'),
    url(r'^api/GetCategoryList/$', get_category_list, name='get_category_list'),
    url(r'^api/get_category_by_name/$', get_category_by_name, name='get_category_by_name'),
    url(r'^api/GetCategoryDetail/(?P<id>[0-9]+)/$', get_category_detail, name='get_category_detail'),
    url(r'^api/EditCategoryDetail/$', edit_category, name='edit_category'),
    url(r'^api/DeleteCategoryDetail/$', delete_category, name='delete_category'),

    # product
    url(r'^ProductListJson/$', ProductListJson.as_view(), name='ProductListJson'),

    url(r'^api/PostProductDetail/$', post_product, name='post_product'),
    url(r'^api/EditProductDetail/$', edit_product, name='edit_product'),
    url(r'^api/GetProductList/$', get_product_list, name='get_product_list'),
    url(r'^api/GetProductDetailByName/$', get_product_detail_by_name, name='get_product_detail_by_name'),
    url(r'^api/GetProductDetail/(?P<id>[0-9]+)/$', get_product_detail, name='get_product_detail'),
    url(r'^api/DeleteProductDetail/$', delete_product, name='delete_product'),
    url(r'^api/get_running_down_out_of_stock_product_list/$', get_running_down_out_of_stock_product_list,
        name='get_running_down_out_of_stock_product_list'),
    url(r'^api/get_last_selling_price_of_the_product_by_customer/$', get_last_selling_price_of_the_product_by_customer,
        name='get_last_selling_price_of_the_product_by_customer'),

    # Company
    url(r'^CompanyListJson/$', CompanyListJson.as_view(), name='CompanyListJson'),
    url(r'^api/PostCompanyDetail/$', post_company, name='post_company'),
    url(r'^api/delete_company/$', delete_company, name='delete_company'),
    url(r'^api/EditCompanyDetail/$', Edit_company, name='Edit_company'),
    url(r'^api/GetCompanyList/$', get_company_list, name='get_company_list'),
    url(r'^api/get_bank_detail/(?P<id>[0-9]+)/$', get_bank_detail, name='get_bank_detail'),
    url(r'^api/get_Company_detail/(?P<id>[0-9]+)/$', get_Company_detail, name='get_Company_detail'),

    # User
    url(r'^UserListJson/$', UserListJson.as_view(), name='UserListJson'),

    url(r'^api/PostUserDetail/$', post_User, name='post_User'),
    url(r'^api/delete_user/$', delete_user, name='delete_user'),
    url(r'^api/get_User_detail/(?P<id>[0-9]+)/$', get_User_detail, name='get_User_detail'),
    url(r'^api/EditUserDetail/$', Edit_user, name='Edit_user'),

    # warehouse
    url(r'^WareHouseListJson/$', WareHouseListJson.as_view(), name='WareHouseListJson'),
    url(r'^api/add_warehouse/$', add_warehouse, name='add_warehouse'),
    url(r'^api/GetWareHouseList/$', GetWareHouseList, name='GetWareHouseList'),
    url(r'^api/GetWareHouseDetail/(?P<id>[0-9]+)/$', get_warehouse_detail, name='get_warehouse_detail'),
    url(r'^api/EditWareHouseDetail/$', edit_warehouse, name='edit_warehouse'),
    url(r'^api/delete_wareHouse/$', delete_wareHouse, name='delete_wareHouse'),

    # unit
    url(r'^UnitsListJson/$', UnitsListJson.as_view(), name='UnitsListJson'),
    url(r'^api/add_unit/$', add_unit, name='add_unit'),

    url(r'^api/get_unit_list/$', get_unit_list, name='get_unit_list'),
    url(r'^api/GetUnitDetail/(?P<id>[0-9]+)/$', get_unit_detail, name='get_unit_detail'),
    url(r'^api/EditUnitDetail/$', edit_unit, name='edit_unit'),

    url(r'^api/delete_unit/$', delete_unit, name='delete_unit'),

    # Sales
    url(r'^SalesListByProductJson/$', SalesListByProductJson.as_view(), name='SalesListByProductJson'),
    url(r'^SalesListJson/$', SalesListJson.as_view(), name='SalesListJson'),
    url(r'^SalesListByCustomerJson/$', SalesListByCustomerJson.as_view(), name='SalesListByCustomerJson'),
    url(r'^api/AddNewSalesDetail/$', add_sales, name='add_sales'),
    url(r'^api/get_sales_detail/(?P<id>[0-9]+)/$', get_sales_detail, name='get_sales_detail'),
    url(r'^api/get_sales_detail_for_invoice/(?P<id>[0-9]+)/$', get_sales_detail_for_invoice,
        name='get_sales_detail_for_invoice'),
    url(r'^api/delete_sales/$', delete_sales, name='delete_sales'),
    url(r'^api/take_sale_payment/$', take_sale_payment, name='take_sale_payment'),

    # Purchase
    url(r'^PurchaseListJson/$', PurchaseListJson.as_view(), name='PurchaseListJson'),
    url(r'^PurchaseListBySupplierJson/$', PurchaseListBySupplierJson.as_view(), name='PurchaseListBySupplierJson'),

    url(r'^api/AddNewPurchaseDetail/$', add_purchase, name='add_purchase'),
    url(r'^api/get_purchase_detail/(?P<id>[0-9]+)/$', get_purchase_detail, name='get_purchase_detail'),
    url(r'^api/delete_purchase/$', delete_purchase, name='delete_purchase'),

    # expense
    url(r'^api/AddNewExpense/$', add_expense, name='add_expense'),
    url(r'^ExpenseListJson/$', ExpenseListJson.as_view(), name='ExpenseListJson'),
    url(r'^api/delete_expense/$', delete_expense, name='delete_expense'),

    # login
    url(r'^postLogin/$', postLogin, name='UserLogin'),

    # change password
    url(r'^change_password/$', change_password, name='change_password'),
    url(r'^get_user_printer/$', get_user_printer, name='get_user_printer'),
    url(r'^api/change_user_printer_setting/$', change_user_printer_setting, name='change_user_printer_setting'),

    # invoice
    url(r'^api/AddNewInvoice/$', add_invoice, name='add_invoice'),
    url(r'^InvoiceListJson/$', InvoiceListJson.as_view(), name='InvoiceListJson'),
    url(r'^api/get_invoice_series_by_company/$', get_invoice_series_by_company, name='get_invoice_series_by_company'),
    url(r'^api/get_new_sale_invoice_number/$', get_new_sale_invoice_number, name='get_new_sale_invoice_number'),

    # back up
    url(r'^api/download_backup/$', download_backup, name='download_backup'),
    url(r'^api/download_expense_report/$', download_expense_report, name='download_expense_report'),
    url(r'^api/download_purchase_report/$', download_purchase_report, name='download_purchase_report'),
    url(r'^api/download_sales_report/$', download_sales_report, name='download_sales_report'),

    #booking
    url(r'^api/add_booking/$', add_booking, name='add_booking'),

nextfifthGSTpro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("home.urls", namespace='homeApp')),
    url(r'^activate/', include("activation.urls", namespace='activationApp')),
    url('', include('pwa.urls')),
]

handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/templates/home/generalsetting.html
{% extends 'home/index.html' %}
{% block title %}
    <title>General Setting</title>
{% endblock %}

{% block body %}

    <div class="column">
        <div class="ui two item stackable tabs menu">
            <div class="item active" onclick="generalSetting(1)" id="securityTab" style="cursor: pointer">
                <p><i class="shield alternate icon"></i>Security</p>
            </div>
            <div class="item" onclick="generalSetting(2)" id="printerTab" style="cursor: pointer">
                <p><i class="print icon"></i>Printer</p>
            </div>

        </div>
    </div>
    <BR>
    <div class="ui main container">
        <div class="ui grid">
            <div class="four wide column"></div>
            <div class="eight wide column">
                <div id="security" class="ui intro tab active" data-tap="Security">
                    <div class="ui segment" style="background-color: #eeeeee; ">
                        <form class="ui form" id="PForm"> {% csrf_token %}
                            <h4 class="ui dividing header" style="text-align: center">Changing Password</h4>
                            <div class="field">
                                <label>Current Password</label>
                                <div class="ui left icon input">
                                    <input placeholder="Current Password" type="password" id="oldPassword">
                                    <i class="lock icon"></i>
                                </div>
                            </div>
                            <div class="field">
                                <label>New Password</label>
                                <div class="ui left icon input">
                                    <input placeholder="New Password" type="password" id="newPassword">
                                    <i class="lock icon"></i>
                                </div>
                            </div>
                            <div class="field">
                                <label>Confirmed Password</label>
                                <div class="ui left icon input">
                                    <input placeholder="Confirmed Password" type="password" id="confirmPassword">
                                    <i class="lock icon"></i>
                                </div>
                            </div>

                            <div style="text-align: center">
                                <button class="ui youtube button" onclick="changePassword()" type="button">
                                    <i class="save icon"></i>
                                    Save
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
                <div id="printer" class="ui tab" dat-tab="Printer">
                    <div class="ui segment "
                         style="background-color: #eeeeee;">
                        <h4 class="ui dividing header" style="text-align: center">Printer Setting</h4>

                        <form class="ui form" id="PrinterForm"> {% csrf_token %}
                            <div class="field">

                                <select class="ui fluid dropdown" id="pID">
                                    {% for p in printers %}
                                        <option value="{{ p.pk }}"  {% if p.pk == myPrinter %}
                                                selected {% endif %} >{{ p.size }}</option>
                                    {% endfor %}

                                </select>
                            </div>

                            <div style="text-align: center">
                                <button class="ui youtube button" onclick="changePrinter()" type="button">
                                    <i class="save icon"></i>
                                    Save
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="four wide column"></div>

        </div>

    </div>

{% endblock %}

{% block js %}
    <script>

        $('.clear.example .button')
            .on('click', function () {
                $('.clear.example .ui.dropdown')
                    .dropdown('clear')
                ;
            })
        ;
        function generalSetting(a) {
            $("#security").hide();
            $("#printer").hide();

            if (a === 1) {
                $("#security").show();
                $("#securityTab").addClass('active');
                $("#printerTab").removeClass('active');

            }

            else if (a === 2) {
                $("#printer").show();
                $("#printerTab").addClass('active');
                $("#securityTab").removeClass('active');

            }

        }

        $('.ui.dropdown')
            .dropdown()
        ;

        $('.tabular.menu .item').tab();


        function changePassword() {
            var newPassword = $('#newPassword').val();
            var oldPassword = $('#oldPassword').val();
            var confirmPassword = $('#confirmPassword').val();

            if (newPassword === '' || oldPassword === '' || confirmPassword === '') {
                $('body')
                    .toast({
                        class: 'orange',
                        message: 'All fields are required !'
                    })
                ;
            }
            else {

                if (newPassword !== confirmPassword) {
                    $('body')
                        .toast({
                            class: 'orange',
                            message: 'Password not matched!'
                        })
                    ;
                }

                else {
                    var csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val();

                    data = new FormData();
                    data.append('newPassword', newPassword);
                    data.append('oldPassword', oldPassword);
                    data.append('csrfmiddlewaretoken', csrfmiddlewaretoken);

                    $.ajax({
                        type: 'post',
                        url: '{% url "homeApp:change_password" %}',
                        data: data,
                        contentType: false,
                        cache: false,
                        processData: false,


                        success: function (response) {
                            if (response.message === 'success') {
                                $('body')
                                    .toast({
                                        class: 'success',
                                        message: 'Password changed successfully'
                                    })
                                ;

                                $('#PForm').trigger('reset');

                            }
                            else {
                                $('body')
                                    .toast({
                                        class: 'warning',
                                        message: '' + response.message
                                    })
                                ;

                            }

                            return response;
                        },
                        error: function () {
                            $('body')
                                .toast({
                                    class: 'error',
                                    message: 'An error occurred !'
                                })
                            ;
                        }
                    });

                }


            }

        }

        function changePrinter() {
            var printerID = $('#pID').val();


            if (printerID === '') {
                $('body')
                    .toast({
                        class: 'orange',
                        message: 'All fields are required !'
                    })
                ;
            }
            else {

                var csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val();

                data = new FormData();
                data.append('printerID', printerID);
                data.append('csrfmiddlewaretoken', csrfmiddlewaretoken);

                $.ajax({
                    type: 'post',
                    url: '{% url "homeApp:change_user_printer_setting" %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('body')
                                .toast({
                                    class: 'success',
                                    message: 'Printer setting changed successfully'
                                })
                            ;

                            $('#PrinterForm').trigger('reset');

                        }
                        else {
                            $('body')
                                .toast({
                                    class: 'warning',
                                    message: '' + response.message
                                })
                            ;

                        }

                        return response;
                    },
                    error: function () {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;
                    }
                });

            }
        }

    </script>


{% endblock %}

home/templates/home/log.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'cssMain/semantic.min.css' %}">
        <link rel="icon" href="{% static 'logo/logo.png' %}" type="image/gif" sizes="16x16">

     <script src="{% static 'jsMain/jquery.min.js' %}"></script>
    <script src="{% static 'jsMain/semantic.min.js' %}"></script>
    <title>Login</title>

<style>
    body{
          background-color: #ACAFB8;
    }
     fieldset {
    border: none;
  }
    .container{
        padding-top: 100px;
    }
     .ui.grid {
        display: flex;
        justify-content: center;
    }
      header {
    background-color: #202731;
    color: #C5C6C8;
    display: block;
    padding: 1.5em;
    text-align: center;
          font-size: 16px;
  }
    .input-wrapper {
      position: relative;
      display: block;
      margin: 2em auto;
      border-bottom: 1px solid #FC7148;
      border-radius: 3px;
      width: 300px;
      padding-left: 20px;
      font-size: 20px;
  }
   input {
        width: 100%;
        line-height: 2;
        background-color: transparent;
        border: none;
        padding: .6em .5em;
        outline: 0;
       color: white;
    }

    .column_1{
        width: 300px;
        height: 400px;
        background-color: #fcffe0;

    }
    .column_2{
         width: 300px;
        height: 400px;
        background-color: #272E38;
    }

     button {
      outline: 0;
      font-size: 12px;
      letter-spacing: 0.1em;
      background-color: #FC7148;
      color: #fff;
      border: none;
      border-radius: 3px;
      width: 200px;
      padding: 1.2em 0;
      margin: 4em auto;
      display: block;
      border-top: 2px solid transparent;
      border-bottom: 2px solid transparent;
  }
    hover {
      border-bottom-color:darkgoldenrod;
    }

     p.hd{
        text-align: center;
        font-variant: small-caps;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        font-size: 30px;
        color: #54caff;
    }
    .credit{
        text-align: center;
        font-size: 18px;
        padding-top: 20px;
    }
</style>
</head>
<body>
    <div class="container">
        <div class="ui equal width center aligned padded grid">
            <div class="ui raised segment" style="background-color: #DCDCDC; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)">
              <div class="ui two column centered grid">
                <div class="column_1" style="width: 350px; padding: 05px">
                    <img class="ui centered medium circular image" src="{% static 'logo/logo.png' %}" style="width: 150px;height: 150px;margin-top: 30px">
                    <br>
                    <p class="hd">NEXT BILL</p>
                </div>
                <div class="column_2" style="width: 350px; padding: 05px">
                    <form id="userLoginForm" action="{% url 'homeApp:UserLogin' %}" method="post">{% csrf_token %}
                    <div  class="login-form-container" >
                        <header>LOGIN</header>
                    <fieldset>
                        <div class="input-wrapper">
                            <input type="text" placeholder="Username" name="userName"  id="userName" />
                        </div>
                        <div class="input-wrapper">
                            <input type="password" placeholder="Password " name="password"  id="password"/>
                        </div>
                        <button style="cursor: pointer" id="continue" type="button" onclick="UserLogin()">CONTINUE</button>
                    </fieldset>
                    </div>
                        </form>
                </div>
              </div>
            </div>
        </div>
    </div>
<p class="credit" style="margin-top: 50px;">Developed by <a href="http://zivainfotech.com" target="_blank">Ziva Infotech</a></p>
    <script>
         function UserLogin() {
        var username = $('#userName').val();
        var password = $('#password').val();

        if(username===""||password===""){


              $('body')
                            .toast({
                                class: 'error',
                                message: 'Username and Password is required !'
                            })
                        ;

            }
            else{
            data = new FormData();
                data.append('userName', username);
                data.append('password', password);

                 $.ajax({
                    type: 'post',
                    url: '{% url 'homeApp:UserLogin' %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('body')
                                .toast({
                                    class: 'success',
                                    message: 'Login Successful.'
                                });
                           document.location.href = "{% url 'homeApp:homepage' %}"
                        }
                        else {
                            $('body')
                                .toast({
                                    class: 'warning',
                                    message: 'Incorrect username or password. Please try again.'
                                })
                            ;

                        }

                        return response;
                    },
                    error: function () {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;
                    }
                });
            }
    }
    </script>
</body>
</html>

home/templates/home/thermalBillPrint.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Invoice</title>
    <link rel="stylesheet" href="{% static 'cssMain/bootstrap.min.css' %}">
    <script src="{% static 'jsMain/jquery.min.js' %}"></script>
    <style>
          @media print {
        body {
{#            width: 80mm;#}
{#            height: 297mm;#}
            margin-left: 3mm;
            margin-bottom: 3mm;
        }

    }
    </style>
</head>
<body onload="myFunction()">

<div id="printDiv" style="width: 80mm;padding: 2mm;">
   <div class="row" style="text-align: center">
       <p> <b>Star Traders</b></p>
       <p>Imphal-Manipur</p>
   </div>
    <div class="row">
        <div class="col-xs-6">Bill No.: {{ sale.pk|stringformat:"05d" }}</div>
        <div class="col-xs-6"> Date: {{ sale.invoiceDate|date:"d-m-Y" }}</div>
    </div>
    <div class="row">
        <table class="table table-striped" style="font-size: 12px!important;">
    <thead>
      <tr>
        <th>Sl.No.</th>
        <th>Item</th>
        <th>Qty</th>
        <th>Rate(₹)</th>
        <th>Total(₹)</th>
      </tr>
    </thead>
    <tbody>
    {% for foo in saleProduct %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ foo.productName }}</td>
        <td>{{ foo.quantity }} {{ foo.unit }}</td>
        <td>{{ foo.rate }}</td>
        <td>{{ foo.total }}</td>
      </tr>
    {% endfor %}

   <tr>
        <td colspan="4" style="text-align: right;font-weight: bold">Sub-Total(₹)</td>
        <td style="font-weight: bold;"> {{ sale.subTotal }}</td>
      </tr>
    <tr>
        <td colspan="4" style="text-align: right;font-weight: bold;border-top: none;">RoundOff(₹)</td>
        <td style="font-weight: bold;border-top: none;"> {{ sale.roundOff }}</td>
      </tr>
    <tr>
        <td colspan="4" style="text-align: right;font-weight: bold;border-top: none;">Discount(₹)</td>
        <td style="font-weight: bold;border-top: none;"> - {{ sale.personalDiscount }}</td>
      </tr>
    <tr>
        <td colspan="4" style="text-align: right;font-weight: bold;border-top: none;">Grand Total(₹)</td>
        <td style="font-weight: bold;border-top: none;"> {{ sale.grandTotal }}</td>
      </tr>


    </tbody>
  </table>
    </div>
    {% comment %}<div class="row" style="float: right;padding-right: 5px;">
        <p>Total : ₹ {{ sale.grandTotal }}</p>
    </div>{% endcomment %}
</div>

<script>

    function myFunction() {
         window.print();
    }
</script>
</body>
</html>